#!bin/bash

attempts=0
while [ $attempts -lt 4 ]
do
attempts=$[$attempts + 1]
read -p"enter username" username
read -s  -p"password" password

len_u=${#username}
len_p=${#password}


if [ $len_u -eq 0 ] || [ $len_p -eq 0 ]
then
        echo " invalid! pls try again "
else
        echo "$username $password" > Data.dat
        exit
        echo"contents saved in Data.dat"
fi

done
