#!bin/bash

attempts=0
while [ $attempts -lt 4 ]
do
attempts=$[$attempts + 1]
read -p"enter username" username
read -s  -p"password" password

len_u=${#username}
len_p=${#password}


if [ $len_u -eq 0 ] || [ $len_p -eq 0 ]
then
        echo " invalid! pls try again "
else
        echo "$username $password" > Data.dat
        exit
        echo"contents saved in Data.dat"
fi

done


siddu@SiddharthReddy:~/endsem$ cat  forloop.sh
#!bin/bash

for file in ./*
do
        if [ -d "$file" ]
        then
                echo "$file is direc"
        elif [ -f "$file" ]
        then
                echo "$file is a file"
        fi
done
siddu@SiddharthReddy:~/endsem$ cat menu.sh
#!bin/bash

echo "options"
echo "1. Todays date"
echo "2.number of users"
echo "3.list of all files"
echo "4.display current dir"

read num
if [ $num -eq 1 ]
then
        d=`date`
        echo $d
fi
num=`who | wc -l`
echo $num
ls
pwd
